# Generated by Django 3.1.1 on 2021-01-09 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='日期')),
                ('earnings', models.FloatField(verbose_name='收益')),
                ('note', models.TextField(max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '理财记录表',
                'verbose_name_plural': '理财记录表',
                'db_table': 'tb_investment',
            },
        ),
    ]
