# Generated by Django 3.1.1 on 2021-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentmodel',
            options={'verbose_name': '理财收益表', 'verbose_name_plural': '理财收益表'},
        ),
        migrations.AlterField(
            model_name='investmentmodel',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
