# Generated by Django 3.1 on 2020-09-02 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='日期')),
                ('salary', models.FloatField(verbose_name='工资')),
                ('save_amount', models.FloatField(verbose_name='存储金')),
                ('budget', models.FloatField(verbose_name='预算')),
                ('rent', models.FloatField(verbose_name='房租')),
                ('salary_day', models.IntegerField(verbose_name='发薪日')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '总账表',
                'verbose_name_plural': '总账表',
                'db_table': 'tb_bill',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DayDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('name', models.CharField(max_length=20, verbose_name='用途')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('type', models.CharField(choices=[('饮食', 'eat'), ('其他', 'other')], max_length=10, verbose_name='类别')),
                ('note', models.TextField(max_length=256, verbose_name='备注')),
                ('bill_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.billmodel', to_field='date', verbose_name='总账')),
            ],
            options={
                'verbose_name': '日记账',
                'verbose_name_plural': '日记账',
                'db_table': 'tb_day_detail',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='billmodel',
            name='detail_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.daydetailmodel', verbose_name='日记账'),
        ),
    ]
