# Generated by Django 3.1 on 2020-09-09 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='发薪日')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('company', models.CharField(max_length=256, verbose_name='在职公司')),
            ],
            options={
                'verbose_name': '发薪日',
                'verbose_name_plural': '发薪日',
                'db_table': 'tb_salary_day',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='daydetailmodel',
            name='type',
            field=models.CharField(choices=[('eat', '饮食'), ('other', '其他')], max_length=10, verbose_name='类别'),
        ),
    ]
